package hibernate;
// Generated 01-feb-2015 23:31:57 by Hibernate Tools 4.3.1



/**
 * FotosInmueble generated by hbm2java
 */
public class FotosInmueble  implements java.io.Serializable {


     private Integer idFoto;
     private Inmuebles inmuebles;
     private String foto;

    public FotosInmueble() {
    }

	
    public FotosInmueble(String foto) {
        this.foto = foto;
    }
    public FotosInmueble(Inmuebles inmuebles, String foto) {
       this.inmuebles = inmuebles;
       this.foto = foto;
    }
   
    public Integer getIdFoto() {
        return this.idFoto;
    }
    
    public void setIdFoto(Integer idFoto) {
        this.idFoto = idFoto;
    }
    public Inmuebles getInmuebles() {
        return this.inmuebles;
    }
    
    public void setInmuebles(Inmuebles inmuebles) {
        this.inmuebles = inmuebles;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }

    public String getFoto(int id) {
        if(inmuebles.getId() == id){
            return this.foto;
        } else {
            return "";
        }
    }


}


