package hibernate;
// Generated 18-feb-2015 19:48:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Inmuebles generated by hbm2java
 */
public class Inmuebles  implements java.io.Serializable {


     private Integer id;
     private String localidad;
     private String direccion;
     private String tipo;
     private int precio;
     private String usuario;
     private Set fotosInmuebles = new HashSet(0);

    public Inmuebles() {
    }

	
    public Inmuebles(String localidad, String direccion, String tipo, int precio) {
        this.localidad = localidad;
        this.direccion = direccion;
        this.tipo = tipo;
        this.precio = precio;
    }
    public Inmuebles(String localidad, String direccion, String tipo, int precio, String usuario, Set fotosInmuebles) {
       this.localidad = localidad;
       this.direccion = direccion;
       this.tipo = tipo;
       this.precio = precio;
       this.usuario = usuario;
       this.fotosInmuebles = fotosInmuebles;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Set getFotosInmuebles() {
        return this.fotosInmuebles;
    }
    
    public void setFotosInmuebles(Set fotosInmuebles) {
        this.fotosInmuebles = fotosInmuebles;
    }




}


